FROM node:24-alpine
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm i
COPY . .
COPY .env.example .env

RUN npx prisma generate
RUN npm install --save-dev nodemon

EXPOSE 4000
CMD ["sh", "-c", "npx prisma migrate deploy && npm run dev:nodemon"]