services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_dev_c
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    networks:
      - library-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    image: home-library:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: api_dev_c
    ports:
      - ${PORT}:4000
      - ${PRISMA_PORT}:5555
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - library-network
    env_file:
      - .env

networks:
  library-network:
    driver: bridge

volumes:
  postgres_data:
